### ISSUE TITLE
Local Playback Support

### ISSUE THREAD

**Issue by DominicMaas** [DominicMaas/SoundByteOSS#38]
This issue is being used to track the progress of local playback support.

## Supported Formats
- .mp3 *(confirmed)*
- .wav
- .ogg
- .flac
- .m4a
- .aif
- .wma
- .mp4 *(confirmed)*

## To-do 

- [x] Set SoundByte as the default music player in Windows 10.
- [ ] Custom icon for music in file explorer (not just the SoundByte logo, follow other app guidelines).
- [x] Ability to open common music files in SoundByte via file explorer.
- [x] Ability to also open video files (such as .mp4) which are also commonly used for audio.
- [x] Ability to open up multiple files and play them in a playlist.
- [x] Video formats (like .mp4) should also play the video in the now playing view (like YouTube videos).
- [x] If only one track is opened, Soundbyte should check the folder for other music as well.
- [ ] Extract the track thumbnail.
- [ ] Liking local music will add the music to an internal likes database.
- [ ] Create local playlists that will be saved to an internal playlist database.
